name: test

on:
  push:
  pull_request:
  schedule:
  - cron: '0 16 * * *'  # UTC 16:00 daily

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # TODO: re-enable aarch64-linux once github native runner supports nested virtualization.
        system: [x86_64-linux]
        version:
        - nixpkgs: nixos-25.05
          home-manager: release-25.05
        - nixpkgs: nixos-unstable
          home-manager: master

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:${{ matrix.version.nixpkgs }}

    - uses: cachix/cachix-action@v16
      env:
        CACHIX_AUTH_TOKEN_PRESENT: ${{ secrets.CACHIX_AUTH_TOKEN != '' }}
      if: ${{ env.CACHIX_AUTH_TOKEN_PRESENT == 'true' }}
      with:
        name: quadlet-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Run tests
      run: >
        nix flake check
        --keep-going
        --all-systems
        --override-input nixpkgs 'github:NixOS/nixpkgs/${{ matrix.version.nixpkgs }}'
        --override-input home-manager 'github:nix-community/home-manager/${{ matrix.version.home-manager }}'
        --override-input test-config "path:$(pwd)/tests/${{ matrix.system }}"
        ./tests

    - name: Build docs
      run: |
        nix build ./docs#book

    - name: Upload docs
      if: matrix.system == 'x86_64-linux' && matrix.version.nixpkgs == 'nixos-unstable'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./result

  publish-docs:
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
