name: test

on:
  push:
  pull_request:
  schedule:
  - cron: '0 16 * * *'  # UTC 16:00 daily

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]
        version:
        - nixpkgs: nixos-24.11
          home-manager: release-24.11
        - nixpkgs: nixos-unstable
          home-manager: master

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:${{ matrix.version.nixpkgs }}

    - run: >
        nix flake check
        --override-input quadlet-nix "path:$(pwd)"
        --override-input nixpkgs 'github:NixOS/nixpkgs/${{ matrix.version.nixpkgs }}'
        --override-input home-manager 'github:nix-community/home-manager/${{ matrix.version.home-manager }}'
        ./tests
